name: Deploy to Appwrite
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Deploy my function to Appwrite
        uses: rdmchr/Appwrite-Deploy@v0.1
        with:
          endpoint: 'https://cloud.appwrite.io/console/project-6528e6b8933eec290236/overview/keys/652a30caec463299571e'
          project: '6528e6b8933eec290236'
          key: '${{ secrets.APPWRITE_API_KEY }}'
