name: Deploy to Appwrite
on:
  push:
    branches:
     - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Deploy my function to Appwrite
        uses: rdmchr/Appwrite-Deploy@v0.1
        with:
          endpoint: 'https://cloud.appwrite.io/console/organization-6528e6b81bda943e3d94'
          project: '6528e6b8933eec290236'
          key: '${{ secrets.APPWRITE_API_KEY }}'
